# Site settings
title: Cerbur Blog
header-img: "img/zhihu.jpg"
tagline: "cn"
description: "一个粉刷匠"
keyword: "Cerbur, Cerbur Blog, gdut, gdutday"
baseurl: ""
google-site-verification: "nSeQMUtlNSQk-V20ALSl4BzLBJ6PSDCgRj1q3KWMR0E"
url: "https://blog.cerbur.club"

# About/contact
owner:
  name: "Cerbur"
  email: cerburyc@gmail.com
  bio: ""

# Data
gavatar:
favicon: favicon.ico

douban_username:
twitter_username:
github_username: Cerbur
facebook_username:
weibo_username:
zhihu_username: bu-zhi-ming-de-xiao-xue-sheng-90

# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

highlighter: rouge
permalink: pretty
paginate: 12
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Cerbur"
      header-img: "img/zhihu.jpg" # We don't want posts without a header image, that whould mean white on white

# Duoshuo settings
duoshuo_username:
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false                     # set to false if you want to use Comment without Sharing

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation

# Gems
plugins: [jekyll-paginate]

# Code Libraries

code-lib-url: https://github.com/Cerbur/Cerbur.github.io/edit/master/code/

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 3              # A tag will be featured if the size of it is more than this condition value

# Friends
friends: [
#     {
#        title: "",
#        href: ""
#     }
]

# Achievements
achievements: [
#     {
#        name: "",
#        detail: "",
#        time: "",
#        img: "",
#        url: ""
#     }
]

#TagDetails
tagDetails: [
    {
       name: "生活",
       content: "你就当这是个Facebook"
    }
    # ,{
    #    name: "",
    #    content: ""
    # }
]
